version: "3.9"

services:
  postgres:
    image: 'postgres:14.2'
    environment:
      - POSTGRES_DB=sberlunch
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/postgres122:/var/lib/postgresql/data

  sberlunch:
    image: 'sberlunch:latest'
    depends_on:
      - postgres
    ports:
      - '3443:3443'
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=sberlunch
      - DB_USER=postgres
      - DB_PASSWORD=password
      - BOT_NAME=${BOT_NAME}
      - BOT_API_KEY=${BOT_API_KEY}